###Get Service document
http://localhost:4004/odata/v4/CatalogService

###Get Service metadata
http://localhost:4004/odata/v4/CatalogService/$metadata

###Get Employee Data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet

###Get V2 Response
http://localhost:4004/odata/v2/CatalogService/EmployeeSet

###Get Sigle Employee Data : TODO: take an id from last call and paste at end
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C197A7FB

###Insert data into employees
POST http://localhost:4004/odata/v4/CatalogService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "Christiano",
  "nameMiddle": null,
  "nameLast": "Ronaldo",
  "nameInitials": null,
  "sex": "M",
  "language": "E",
  "phoneNumber": null,
  "email": "chris@anubhavtrainings.com",
  "loginName": "RONALDOCR",
  "Currency_code": "USD",
  "salaryAmount": 100000,
  "accountNumber": "9988776655",
  "bankId": "121000358",
  "bankName": "HDFC Bank"
}

###Update employee data

PATCH http://localhost:4004/odata/v4/CatalogService/EmployeeSet/a7b5141a-8299-4403-962b-7838c5e371e0
Content-Type: application/json

{
    "salaryAmount":100000,
    "Currency_code":"EUR"
}

###Get the employee
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/4958a0e3-8507-46a1-b357-8d3b8566fd73

###Delete the data
DELETE http://localhost:4004/odata/v4/CatalogService/EmployeeSet/4958a0e3-8507-46a1-b357-8d3b8566fd73

###Load data chunk by chunk - pagination
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=2&$skip=2

###Filter data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=bankName eq 'My Bank of San Francisco'

###filter by the pattern search
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=contains(nameLast,'Wall')

###Count the records
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/$count

###Get All the Purchase orders
http://localhost:4004/odata/v4/CatalogService/POs

###Get single order
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2A052?$expand=Items

###Get CDS data for product
http://localhost:4004/odata/v4/CatalogService/ProductView/74867AD200E41EDBA5D8B06B26EB4052?$expand=To_Items

###Boost action
POST http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC28052/boost
Content-Type: application/json

{}

###Calling the functions
http://localhost:4004/odata/v4/CatalogService/getLargestOrder()

###Send the service call
http://localhost:4004/odata/v4/MyService/ReadEmployeeSrv